BTS-619: Remove pure python stuff
jampp/sharedbuffers pull request #100
Opened 2022-06-09 18:46 UTC by chpedersen

2022-06-09 19:55 UTC, chpedersen commented on sharedbuffers/mapped_struct.py
>          else:
Ok, I don't remember why I did this, but the tests pass :shrug:

2022-06-09 19:55 UTC, chpedersen commented on sharedbuffers/mapped_struct.py
>              return cython.cast(proxied_frozenset, self)._subset(seq, False)
same here

2022-06-15 14:37 UTC, marianoSecure approved these changes

2022-06-15 15:07 UTC, klaussfreire requested changes

2022-06-15 15:07 UTC, klaussfreire commented on sharedbuffers/mapped_struct.py
> +        return proxied_list_cmp(self, other)
This was "if not cython.compiled"... shouldn't this have been deleted?

I don't see cython code for the comparison. Which is weird.

I think proxied_list should have a richcmp method like proxied_tuple... not sure why it isn't there.

2022-06-15 15:07 UTC, klaussfreire commented on sharedbuffers/mapped_struct.py
> -                self._hash = hash(tuple(iter(self)))
I think the else path is still needed

2022-06-15 15:21 UTC, marianoSecure commented on sharedbuffers/mapped_struct.py
> -                self._hash = hash(tuple(iter(self)))
I think its being hashed correctly in line 2525

2022-06-21 18:53 UTC, klaussfreire commented on sharedbuffers/mapped_struct.py
> -                self._hash = hash(tuple(iter(self)))
pypy is not cpython

2022-06-21 18:57 UTC, klaussfreire approved these changes

2022-06-21 18:57 UTC, klaussfreire commented on sharedbuffers/mapped_struct.py
> -                self._hash = hash(tuple(iter(self)))
And cython != cpython (one very significant letter of difference)

2022-06-27 18:35 UTC, merged