Issue 24 lz4 frame module
jampp/sharedbuffers pull request #25
Opened 2018-01-03 17:45 UTC by tzulberti-jampp

2018-01-03 17:57 UTC, klaussfreire requested changes
Nope. They're not interchangeable. A change like this needs far more care and at least a minor bump. Also a version change in the file format, and compatibility code when reading the old format.

2018-01-03 18:26 UTC, tzulberti-jampp commented
If I understand correctly the version bump is required because what the file created with lz4 0.8.1 is going to be imcompatible with the one created with version 0.18.1. Not because of the difference on code...

I googled who to make lz4 compatible between versions but I wasn't able to find any information about this. Do you have an idea on who to make those versions compatible?

2018-01-03 19:52 UTC, klaussfreire commented
Yes. Use the file format version embedded in the bundles and have both versions of the code.

2018-01-03 19:53 UTC, klaussfreire commented
It will probably be more efficient to talk about it in person tomorrow

2018-01-08 17:07 UTC, klaussfreire requested changes

2018-01-08 17:07 UTC, klaussfreire commented on sharedbuffers/mapped_struct.py
> +    lz4_functions_module = lz4.block
lz4_block?

2018-01-10 14:06 UTC, klaussfreire approved these changes

2018-01-10 14:55 UTC, zeitos approved these changes
LGTM

2018-01-10 14:55 UTC, merged